name: Build
on:
  push:
    branches:
      - server-client
  workflow_dispatch:

jobs:
  build-windwos-client:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r client/requirements_windows.txt

      - name: Build application
        run: |
          python client/setup.py build
        shell: cmd

      - name: Archive build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-windows
          path: build/exe.*

      - name: set env
        run: echo "NOW=%date:~10,4%.%date:~4,2%.%date:~7,2%" >> %GITHUB_ENV%
        shell: cmd

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: windows-client-${{ env.NOW }}
          release_name: Release Client Windows
          draft: false
          prerelease: false

      - name: Zip the build directory
        #run: zip -r build/linux-client.zip build/exe.linux-x86_64-3.11
        run: Compress-Archive -Path build/exe.win-amd64-3.11 -DestinationPath build/windows-client.zip
        shell: pwsh

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/windows-client.zip
          asset_name: windows-client.zip
          asset_content_type: application/zip
